delete from DEPARTMENT;
Insert into DEPARTMENT values(1, 'АСОиУ','Никонов А.В.',383456,'ФИТиКС');
Insert into DEPARTMENT values(2, 'Информ. безопасность','Павлов Д.В.',383457,'РТФ');
Insert into DEPARTMENT values(3, 'БЖД','Куклачев И.С.',383463,'нет');
Insert into DEPARTMENT values(4, 'Физика','Исаев К.Л.',383489,'нет');
Insert into DEPARTMENT values(5, 'Математика','Леонов П.Д.',383321,'нет');
Insert into DEPARTMENT values(6, 'МО','Шкилева В.О.',383478,'ФИТиКС');
Insert into DEPARTMENT values(7, 'ИВТ','Смирнов Н.Ю.',383454,'ФИТиКС');
Insert into DEPARTMENT values(8, 'Робототехника','Цветаев Д.Д.',383453,'ФИТиКС');
Insert into DEPARTMENT values(9, 'Юриспруденция','Полаев Е.Ф.',383412,'ФГО');
Insert into DEPARTMENT values(10, 'Дизайн','Давыдов Ф.М.',383789,'ФГО');
Insert into DEPARTMENT values(11, 'Иностанных языков','Федоров М.И.',383356,'нет');
Commit;