CREATE OR REPLACE PROCEDURE Department_Name(p_department_name out VARCHAR2,
p_hall_id IN int) IS
BEGIN
SELECT DEPARTMENT.DEPARTMENT_NAME INTO p_department_name FROM DEPARTMENT WHERE DEPARTMENT.DEPARTMENT_ID=(SELECT HALL.DEPARTMENT_ID FROM HALL WHERE HALL.HALL_ID = p_hall_id);
END;
