SELECT hall_id, HALL_SQUARE, HALL_WINDOWS, HEATING,HALL_TARGET, HALL_CHIEF, DEPARTMENT_NAME
FROM HALL JOIN DEPARTMENT 
ON HALL.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID 
ORDER BY DEPARTMENT.DEPARTMENT_NAME;
COMMIT;
