USE University
GO
CREATE TABLE T1(col1 INT not null primary key);
ALTER TABLE T1 ADD col2 int null;
ALTER TABLE T1 ALTER COLUMN col2 INT NOT NULL;
CREATE NONCLUSTERED INDEX idx1 ON T1(col1);
DROP TABLE T1;
GO